import { Canvas } from '@react-three/fiber';
import { OrbitControls, Grid, Environment } from '@react-three/drei';
import { STLModel } from '@/components/cad/STLModel';
import { ProgressiveFluxLoader } from '@/components/ui/progressive-flux-loader';
import { PARAM_PHASES } from '@/lib/constants';

interface PreviewPanelProps {
  stlUrl: string | null;
  paramUpdateKey: number;
  isParamUpdating: boolean;
  provider: string;
}

export function PreviewPanel({ stlUrl, paramUpdateKey, isParamUpdating, provider }: PreviewPanelProps) {
  return (
    <div className="flex-1 flex h-full w-full items-center justify-center bg-[#292828] relative">
      <Canvas
        camera={{ position: [80, 80, 80], fov: 45 }}
        gl={{ preserveDrawingBuffer: true, antialias: true }}
        shadows
        className="w-full h-full"
      >
        <ambientLight intensity={0.4} />
        <directionalLight position={[50, 50, 50]} intensity={1.2} castShadow />
        <directionalLight position={[-30, 20, -20]} intensity={0.3} />
        <Environment preset="city" />
        <Grid
          args={[200, 200]}
          cellSize={5}
          cellThickness={0.5}
          cellColor="#333"
          sectionSize={50}
          sectionThickness={1}
          sectionColor="#555"
          fadeDistance={300}
          infiniteGrid
        />
        {stlUrl && (
          <STLModel
            key={`${stlUrl}-${paramUpdateKey}`}
            url={stlUrl}
            updating={isParamUpdating}
          />
        )}
        <OrbitControls enableDamping dampingFactor={0.1} />
      </Canvas>

      {!stlUrl && (
        <div className="absolute flex items-center justify-center pointer-events-none">
          <span className="text-sm text-adam-text-secondary">Send a message to start creating</span>
        </div>
      )}

      {stlUrl && (
        <div className="absolute top-3 left-3 glass-effect rounded-lg px-3 py-1.5 text-[10px] text-adam-text-secondary">
          Generated by {provider}
        </div>
      )}

      {isParamUpdating && (
        <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
          <div className="glass-effect rounded-xl px-8 py-6 w-80">
            <ProgressiveFluxLoader
              phases={PARAM_PHASES}
              showLabel
              className="gap-3"
              barClassName="h-2"
              textClassName="text-sm"
            />
          </div>
        </div>
      )}
    </div>
  );
}
